### ISSUE TITLE
Images for README

### ISSUE THREAD

**Issue by garetWk** [garetWk/TD-Gammon#1]
![gammonnetwork](https://cloud.githubusercontent.com/assets/7111116/24832397/f46e7b34-1c74-11e7-9e5e-926febf2b423.png)
![evaluation](https://cloud.githubusercontent.com/assets/7111116/24832398/f71f6c6c-1c74-11e7-9151-8f05c38498d6.PNG)
![gameboard](https://cloud.githubusercontent.com/assets/7111116/24832412/3949c0f6-1c75-11e7-8d39-88f32585ad73.PNG)

**Comment by KnightTim** [comment]
Only needed for readme, not a real issue.
